---
name: Task-Perl-Critic-IncludingOptionalDependencies
version: 1.003
author:
  - 'Elliot Shank <perl@galumph.com>'
abstract: Install everything Perl::Critic plus its optional dependencies.
license: perl
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  Repository: http://perlcritic.tigris.org/svn/perlcritic/trunk/Task-Perl-Critic/
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
requires:
  File::HomeDir: 0
  File::Which: 0
  IPC::Open2: 1
  Perl::MinimumVersion: 0
  Perl::Tidy: 0
  Pod::Spell: 1
  Regexp::Parser: 0.2
  Task::Perl::Critic: 1.005
  Term::ANSIColor: 0
  Text::ParseWords: 3
build_requires:
  Test::More: 0
dynamic_config: 0
provides:
  Task::Perl::Critic::IncludingOptionalDependencies:
    file: lib/Task/Perl/Critic/IncludingOptionalDependencies.pm
    version: 1.003
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
