---
abstract: 'Install everything Perl::Critic plus its optional dependencies.'
author:
  - 'Elliot Shank <perl@galumph.com>'
build_requires:
  Test::More: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 0
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Perl-Critic-IncludingOptionalDependencies
provides:
  Task::Perl::Critic::IncludingOptionalDependencies:
    file: lib/Task/Perl/Critic/IncludingOptionalDependencies.pm
    version: 1.005
requires:
  File::HomeDir: 0
  File::Which: 0
  IPC::Open2: 1
  PPIx::Regexp: 0
  Perl::MinimumVersion: 0
  Perl::Tidy: 0
  Pod::Spell: 1
  Readonly::XS: 0
  Task::Perl::Critic: 1.006
  Term::ANSIColor: 0
  Text::ParseWords: 3
resources:
  MailingList: http://perlcritic.tigris.org/servlets/SummarizeList?listName=users
  homepage: http://perlcritic.com
  license: http://dev.perl.org/licenses/
  repository: http://guest@perlcritic.tigris.org/svn/perlcritic/trunk/distributions/Task-Perl-Critic/
version: 1.005
